// Prayer mat product data
export const prayerMats = [
  {
    id: 1,
    name: 'Premium Prayer Mat',
    price: 299.00,
    image: '/img/1.jpg',
    material: 'Premium Silk Blend',
    description: 'Ultra-soft silk blend with Arabic calligraphy',
  },
  {
    id: 2,
    name: 'Heritage Prayer Mat',
    price: 399.00,
    image: '/img/2.jpg',
    material: 'Pure Merino Wool',
    description: 'Hand-woven with traditional patterns',
  },
  {
    id: 3,
    name: 'Classic Prayer Mat',
    price: 249.00,
    image: '/img/3.jpg',
    material: 'Organic Cotton Canvas',
    description: 'Clean lines, sacred geometry',
  },
  {
    id: 4,
    name: 'Luxury Prayer Mat',
    price: 499.00,
    image: '/img/4.jpg',
    material: 'Silk with Gold Thread',
    description: 'Luxury embroidered masterpiece',
  },
  {
    id: 5,
    name: 'Elegant Prayer Mat',
    price: 349.00,
    originalPrice: 399.00,
    image: '/img/5.jpg',
    material: 'Linen Blend',
    description: 'Warm earth tones, comfortable',
  },
  {
    id: 6,
    name: 'Modern Prayer Mat',
    price: 279.00,
    image: '/img/6.jpg',
    material: 'Recycled Fibers',
    description: 'Eco-conscious, timeless design',
  },
  {
    id: 7,
    name: 'Deluxe Prayer Mat',
    price: 449.00,
    originalPrice: 599.00,
    image: '/img/7.jpg',
    material: 'Premium Cotton',
    description: 'Handcrafted with care',
  },
];
